/**
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import polytech.spaceteam.cineditor.CinEditorRuntimeModule;
import polytech.spaceteam.cineditor.CinEditorStandaloneSetup;
import polytech.spaceteam.cineditor.ide.CinEditorIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CinEditorIdeSetup extends CinEditorStandaloneSetup {
  @Override
  public Injector createInjector() {
    CinEditorRuntimeModule _cinEditorRuntimeModule = new CinEditorRuntimeModule();
    CinEditorIdeModule _cinEditorIdeModule = new CinEditorIdeModule();
    return Guice.createInjector(Modules2.mixin(_cinEditorRuntimeModule, _cinEditorIdeModule));
  }
}
