/*
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CinEditorGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MovieElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Movie");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMovieKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cPositionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPositionPositionParserRuleCall_2_0 = (RuleCall)cPositionAssignment_2.eContents().get(0);
		private final Assignment cLayersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLayersLayerParserRuleCall_3_0 = (RuleCall)cLayersAssignment_3.eContents().get(0);
		
		//Movie:
		//	'Movie' name=EString position=Position
		//	layers+=Layer+;
		@Override public ParserRule getRule() { return rule; }
		
		//'Movie' name=EString position=Position layers+=Layer+
		public Group getGroup() { return cGroup; }
		
		//'Movie'
		public Keyword getMovieKeyword_0() { return cMovieKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//position=Position
		public Assignment getPositionAssignment_2() { return cPositionAssignment_2; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_2_0() { return cPositionPositionParserRuleCall_2_0; }
		
		//layers+=Layer+
		public Assignment getLayersAssignment_3() { return cLayersAssignment_3; }
		
		//Layer
		public RuleCall getLayersLayerParserRuleCall_3_0() { return cLayersLayerParserRuleCall_3_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTextParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPictureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVideoParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFadeInParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cFadeOutParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cTranslateParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cRectangleParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Element:
		//	Text | Picture | Video | FadeIn | FadeOut | Translate | Rectangle;
		@Override public ParserRule getRule() { return rule; }
		
		//Text | Picture | Video | FadeIn | FadeOut | Translate | Rectangle
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Text
		public RuleCall getTextParserRuleCall_0() { return cTextParserRuleCall_0; }
		
		//Picture
		public RuleCall getPictureParserRuleCall_1() { return cPictureParserRuleCall_1; }
		
		//Video
		public RuleCall getVideoParserRuleCall_2() { return cVideoParserRuleCall_2; }
		
		//FadeIn
		public RuleCall getFadeInParserRuleCall_3() { return cFadeInParserRuleCall_3; }
		
		//FadeOut
		public RuleCall getFadeOutParserRuleCall_4() { return cFadeOutParserRuleCall_4; }
		
		//Translate
		public RuleCall getTranslateParserRuleCall_5() { return cTranslateParserRuleCall_5; }
		
		//Rectangle
		public RuleCall getRectangleParserRuleCall_6() { return cRectangleParserRuleCall_6; }
	}
	public class LayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Layer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLayerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLayerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsElementParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		
		//Layer:
		//	{Layer}
		//	'Layer'
		//	elements+=Element+;
		@Override public ParserRule getRule() { return rule; }
		
		//{Layer} 'Layer' elements+=Element+
		public Group getGroup() { return cGroup; }
		
		//{Layer}
		public Action getLayerAction_0() { return cLayerAction_0; }
		
		//'Layer'
		public Keyword getLayerKeyword_1() { return cLayerKeyword_1; }
		
		//elements+=Element+
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }
		
		//Element
		public RuleCall getElementsElementParserRuleCall_2_0() { return cElementsElementParserRuleCall_2_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class PositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Position");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPositionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cWidthAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cWidthEIntParserRuleCall_1_0 = (RuleCall)cWidthAssignment_1.eContents().get(0);
		private final Keyword cXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cHeightAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHeightEIntParserRuleCall_3_0 = (RuleCall)cHeightAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cXAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cXEIntParserRuleCall_4_1_0 = (RuleCall)cXAssignment_4_1.eContents().get(0);
		private final Keyword cCommaKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Assignment cYAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cYEIntParserRuleCall_4_3_0 = (RuleCall)cYAssignment_4_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		
		//Position:
		//	'position' width=EInt 'x' height=EInt ('(' x=EInt ',' y=EInt ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'position' width=EInt 'x' height=EInt ('(' x=EInt ',' y=EInt ')')?
		public Group getGroup() { return cGroup; }
		
		//'position'
		public Keyword getPositionKeyword_0() { return cPositionKeyword_0; }
		
		//width=EInt
		public Assignment getWidthAssignment_1() { return cWidthAssignment_1; }
		
		//EInt
		public RuleCall getWidthEIntParserRuleCall_1_0() { return cWidthEIntParserRuleCall_1_0; }
		
		//'x'
		public Keyword getXKeyword_2() { return cXKeyword_2; }
		
		//height=EInt
		public Assignment getHeightAssignment_3() { return cHeightAssignment_3; }
		
		//EInt
		public RuleCall getHeightEIntParserRuleCall_3_0() { return cHeightEIntParserRuleCall_3_0; }
		
		//('(' x=EInt ',' y=EInt ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_0() { return cLeftParenthesisKeyword_4_0; }
		
		//x=EInt
		public Assignment getXAssignment_4_1() { return cXAssignment_4_1; }
		
		//EInt
		public RuleCall getXEIntParserRuleCall_4_1_0() { return cXEIntParserRuleCall_4_1_0; }
		
		//','
		public Keyword getCommaKeyword_4_2() { return cCommaKeyword_4_2; }
		
		//y=EInt
		public Assignment getYAssignment_4_3() { return cYAssignment_4_3; }
		
		//EInt
		public RuleCall getYEIntParserRuleCall_4_3_0() { return cYEIntParserRuleCall_4_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Text");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextEStringParserRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Assignment cPositionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPositionPositionParserRuleCall_4_0 = (RuleCall)cPositionAssignment_4.eContents().get(0);
		private final Keyword cAtKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cBeginTimeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cBeginTimeEIntParserRuleCall_6_0 = (RuleCall)cBeginTimeAssignment_6.eContents().get(0);
		private final Keyword cDuringKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDurationAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDurationEIntParserRuleCall_8_0 = (RuleCall)cDurationAssignment_8.eContents().get(0);
		
		//Text:
		//	'Text' name=EString '->' text=EString position=Position 'at' beginTime=EInt 'during' duration=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'Text' name=EString '->' text=EString position=Position 'at' beginTime=EInt 'during' duration=EInt
		public Group getGroup() { return cGroup; }
		
		//'Text'
		public Keyword getTextKeyword_0() { return cTextKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//text=EString
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_3_0() { return cTextEStringParserRuleCall_3_0; }
		
		//position=Position
		public Assignment getPositionAssignment_4() { return cPositionAssignment_4; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_4_0() { return cPositionPositionParserRuleCall_4_0; }
		
		//'at'
		public Keyword getAtKeyword_5() { return cAtKeyword_5; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_6() { return cBeginTimeAssignment_6; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_6_0() { return cBeginTimeEIntParserRuleCall_6_0; }
		
		//'during'
		public Keyword getDuringKeyword_7() { return cDuringKeyword_7; }
		
		//duration=EInt
		public Assignment getDurationAssignment_8() { return cDurationAssignment_8; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_8_0() { return cDurationEIntParserRuleCall_8_0; }
	}
	public class PictureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Picture");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPictureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUrlAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUrlEStringParserRuleCall_4_0 = (RuleCall)cUrlAssignment_4.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPositionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPositionPositionParserRuleCall_6_0 = (RuleCall)cPositionAssignment_6.eContents().get(0);
		private final Keyword cAtKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cBeginTimeAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cBeginTimeEIntParserRuleCall_8_0 = (RuleCall)cBeginTimeAssignment_8.eContents().get(0);
		private final Keyword cDuringKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDurationAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDurationEIntParserRuleCall_10_0 = (RuleCall)cDurationAssignment_10.eContents().get(0);
		
		//Picture:
		//	'Picture' name=EString '->' '"' url=EString '"' position=Position 'at' beginTime=EInt 'during' duration=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'Picture' name=EString '->' '"' url=EString '"' position=Position 'at' beginTime=EInt 'during' duration=EInt
		public Group getGroup() { return cGroup; }
		
		//'Picture'
		public Keyword getPictureKeyword_0() { return cPictureKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_3() { return cQuotationMarkKeyword_3; }
		
		//url=EString
		public Assignment getUrlAssignment_4() { return cUrlAssignment_4; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_4_0() { return cUrlEStringParserRuleCall_4_0; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_5() { return cQuotationMarkKeyword_5; }
		
		//position=Position
		public Assignment getPositionAssignment_6() { return cPositionAssignment_6; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_6_0() { return cPositionPositionParserRuleCall_6_0; }
		
		//'at'
		public Keyword getAtKeyword_7() { return cAtKeyword_7; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_8() { return cBeginTimeAssignment_8; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_8_0() { return cBeginTimeEIntParserRuleCall_8_0; }
		
		//'during'
		public Keyword getDuringKeyword_9() { return cDuringKeyword_9; }
		
		//duration=EInt
		public Assignment getDurationAssignment_10() { return cDurationAssignment_10; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_10_0() { return cDurationEIntParserRuleCall_10_0; }
	}
	public class VideoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Video");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVideoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuotationMarkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUrlAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUrlEStringParserRuleCall_4_0 = (RuleCall)cUrlAssignment_4.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cFromKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cBeginCropTimeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cBeginCropTimeEIntParserRuleCall_7_0 = (RuleCall)cBeginCropTimeAssignment_7.eContents().get(0);
		private final Assignment cPositionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPositionPositionParserRuleCall_8_0 = (RuleCall)cPositionAssignment_8.eContents().get(0);
		private final Keyword cAtKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cBeginTimeAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cBeginTimeEIntParserRuleCall_10_0 = (RuleCall)cBeginTimeAssignment_10.eContents().get(0);
		private final Keyword cDuringKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cDurationAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cDurationEIntParserRuleCall_12_0 = (RuleCall)cDurationAssignment_12.eContents().get(0);
		
		//Video:
		//	'Video' name=EString '->' '"' url=EString '"' 'from' beginCropTime=EInt position=Position 'at' beginTime=EInt
		//	'during' duration=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'Video' name=EString '->' '"' url=EString '"' 'from' beginCropTime=EInt position=Position 'at' beginTime=EInt 'during'
		//duration=EInt
		public Group getGroup() { return cGroup; }
		
		//'Video'
		public Keyword getVideoKeyword_0() { return cVideoKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_3() { return cQuotationMarkKeyword_3; }
		
		//url=EString
		public Assignment getUrlAssignment_4() { return cUrlAssignment_4; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_4_0() { return cUrlEStringParserRuleCall_4_0; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_5() { return cQuotationMarkKeyword_5; }
		
		//'from'
		public Keyword getFromKeyword_6() { return cFromKeyword_6; }
		
		//beginCropTime=EInt
		public Assignment getBeginCropTimeAssignment_7() { return cBeginCropTimeAssignment_7; }
		
		//EInt
		public RuleCall getBeginCropTimeEIntParserRuleCall_7_0() { return cBeginCropTimeEIntParserRuleCall_7_0; }
		
		//position=Position
		public Assignment getPositionAssignment_8() { return cPositionAssignment_8; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_8_0() { return cPositionPositionParserRuleCall_8_0; }
		
		//'at'
		public Keyword getAtKeyword_9() { return cAtKeyword_9; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_10() { return cBeginTimeAssignment_10; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_10_0() { return cBeginTimeEIntParserRuleCall_10_0; }
		
		//'during'
		public Keyword getDuringKeyword_11() { return cDuringKeyword_11; }
		
		//duration=EInt
		public Assignment getDurationAssignment_12() { return cDurationAssignment_12; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_12_0() { return cDurationEIntParserRuleCall_12_0; }
	}
	public class FadeInElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.FadeIn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFadeInKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cAtKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBeginTimeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBeginTimeEIntParserRuleCall_5_0 = (RuleCall)cBeginTimeAssignment_5.eContents().get(0);
		private final Keyword cDuringKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDurationAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDurationEIntParserRuleCall_7_0 = (RuleCall)cDurationAssignment_7.eContents().get(0);
		private final Keyword cOnKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cElementAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cElementElementCrossReference_9_0 = (CrossReference)cElementAssignment_9.eContents().get(0);
		private final RuleCall cElementElementIDTerminalRuleCall_9_0_1 = (RuleCall)cElementElementCrossReference_9_0.eContents().get(1);
		
		//FadeIn:
		//	'Effect' name=EString '->' 'FadeIn' 'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element];
		@Override public ParserRule getRule() { return rule; }
		
		//'Effect' name=EString '->' 'FadeIn' 'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element]
		public Group getGroup() { return cGroup; }
		
		//'Effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'FadeIn'
		public Keyword getFadeInKeyword_3() { return cFadeInKeyword_3; }
		
		//'at'
		public Keyword getAtKeyword_4() { return cAtKeyword_4; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_5() { return cBeginTimeAssignment_5; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_5_0() { return cBeginTimeEIntParserRuleCall_5_0; }
		
		//'during'
		public Keyword getDuringKeyword_6() { return cDuringKeyword_6; }
		
		//duration=EInt
		public Assignment getDurationAssignment_7() { return cDurationAssignment_7; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_7_0() { return cDurationEIntParserRuleCall_7_0; }
		
		//'on'
		public Keyword getOnKeyword_8() { return cOnKeyword_8; }
		
		//element=[Element]
		public Assignment getElementAssignment_9() { return cElementAssignment_9; }
		
		//[Element]
		public CrossReference getElementElementCrossReference_9_0() { return cElementElementCrossReference_9_0; }
		
		//ID
		public RuleCall getElementElementIDTerminalRuleCall_9_0_1() { return cElementElementIDTerminalRuleCall_9_0_1; }
	}
	public class FadeOutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.FadeOut");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFadeOutKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cAtKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBeginTimeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBeginTimeEIntParserRuleCall_5_0 = (RuleCall)cBeginTimeAssignment_5.eContents().get(0);
		private final Keyword cDuringKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDurationAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDurationEIntParserRuleCall_7_0 = (RuleCall)cDurationAssignment_7.eContents().get(0);
		private final Keyword cOnKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cElementAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cElementElementCrossReference_9_0 = (CrossReference)cElementAssignment_9.eContents().get(0);
		private final RuleCall cElementElementIDTerminalRuleCall_9_0_1 = (RuleCall)cElementElementCrossReference_9_0.eContents().get(1);
		
		//FadeOut:
		//	'Effect' name=EString '->' 'FadeOut' 'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element];
		@Override public ParserRule getRule() { return rule; }
		
		//'Effect' name=EString '->' 'FadeOut' 'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element]
		public Group getGroup() { return cGroup; }
		
		//'Effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'FadeOut'
		public Keyword getFadeOutKeyword_3() { return cFadeOutKeyword_3; }
		
		//'at'
		public Keyword getAtKeyword_4() { return cAtKeyword_4; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_5() { return cBeginTimeAssignment_5; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_5_0() { return cBeginTimeEIntParserRuleCall_5_0; }
		
		//'during'
		public Keyword getDuringKeyword_6() { return cDuringKeyword_6; }
		
		//duration=EInt
		public Assignment getDurationAssignment_7() { return cDurationAssignment_7; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_7_0() { return cDurationEIntParserRuleCall_7_0; }
		
		//'on'
		public Keyword getOnKeyword_8() { return cOnKeyword_8; }
		
		//element=[Element]
		public Assignment getElementAssignment_9() { return cElementAssignment_9; }
		
		//[Element]
		public CrossReference getElementElementCrossReference_9_0() { return cElementElementCrossReference_9_0; }
		
		//ID
		public RuleCall getElementElementIDTerminalRuleCall_9_0_1() { return cElementElementIDTerminalRuleCall_9_0_1; }
	}
	public class TranslateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Translate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTranslateKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPixelsToTranslateHorizontallyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPixelsToTranslateHorizontallyEIntParserRuleCall_5_0 = (RuleCall)cPixelsToTranslateHorizontallyAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPixelsToTranslateVerticallyAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPixelsToTranslateVerticallyEIntParserRuleCall_7_0 = (RuleCall)cPixelsToTranslateVerticallyAssignment_7.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cAtKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cBeginTimeAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cBeginTimeEIntParserRuleCall_10_0 = (RuleCall)cBeginTimeAssignment_10.eContents().get(0);
		private final Keyword cDuringKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cDurationAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cDurationEIntParserRuleCall_12_0 = (RuleCall)cDurationAssignment_12.eContents().get(0);
		private final Keyword cOnKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cElementAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final CrossReference cElementElementCrossReference_14_0 = (CrossReference)cElementAssignment_14.eContents().get(0);
		private final RuleCall cElementElementIDTerminalRuleCall_14_0_1 = (RuleCall)cElementElementCrossReference_14_0.eContents().get(1);
		
		//Translate:
		//	'Effect' name=EString '->' 'Translate' '(' pixelsToTranslateHorizontally=EInt ',' pixelsToTranslateVertically=EInt
		//	')' 'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element];
		@Override public ParserRule getRule() { return rule; }
		
		//'Effect' name=EString '->' 'Translate' '(' pixelsToTranslateHorizontally=EInt ',' pixelsToTranslateVertically=EInt ')'
		//'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element]
		public Group getGroup() { return cGroup; }
		
		//'Effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'Translate'
		public Keyword getTranslateKeyword_3() { return cTranslateKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//pixelsToTranslateHorizontally=EInt
		public Assignment getPixelsToTranslateHorizontallyAssignment_5() { return cPixelsToTranslateHorizontallyAssignment_5; }
		
		//EInt
		public RuleCall getPixelsToTranslateHorizontallyEIntParserRuleCall_5_0() { return cPixelsToTranslateHorizontallyEIntParserRuleCall_5_0; }
		
		//','
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
		
		//pixelsToTranslateVertically=EInt
		public Assignment getPixelsToTranslateVerticallyAssignment_7() { return cPixelsToTranslateVerticallyAssignment_7; }
		
		//EInt
		public RuleCall getPixelsToTranslateVerticallyEIntParserRuleCall_7_0() { return cPixelsToTranslateVerticallyEIntParserRuleCall_7_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'at'
		public Keyword getAtKeyword_9() { return cAtKeyword_9; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_10() { return cBeginTimeAssignment_10; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_10_0() { return cBeginTimeEIntParserRuleCall_10_0; }
		
		//'during'
		public Keyword getDuringKeyword_11() { return cDuringKeyword_11; }
		
		//duration=EInt
		public Assignment getDurationAssignment_12() { return cDurationAssignment_12; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_12_0() { return cDurationEIntParserRuleCall_12_0; }
		
		//'on'
		public Keyword getOnKeyword_13() { return cOnKeyword_13; }
		
		//element=[Element]
		public Assignment getElementAssignment_14() { return cElementAssignment_14; }
		
		//[Element]
		public CrossReference getElementElementCrossReference_14_0() { return cElementElementCrossReference_14_0; }
		
		//ID
		public RuleCall getElementElementIDTerminalRuleCall_14_0_1() { return cElementElementIDTerminalRuleCall_14_0_1; }
	}
	public class RectangleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Rectangle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRectangleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cHexadecimalValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHexadecimalValueEStringParserRuleCall_3_0 = (RuleCall)cHexadecimalValueAssignment_3.eContents().get(0);
		private final Assignment cPositionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPositionPositionParserRuleCall_4_0 = (RuleCall)cPositionAssignment_4.eContents().get(0);
		private final Keyword cAtKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cBeginTimeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cBeginTimeEIntParserRuleCall_6_0 = (RuleCall)cBeginTimeAssignment_6.eContents().get(0);
		private final Keyword cDuringKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDurationAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDurationEIntParserRuleCall_8_0 = (RuleCall)cDurationAssignment_8.eContents().get(0);
		
		//Rectangle:
		//	'Rectangle' name=EString '->' hexadecimalValue=EString position=Position 'at' beginTime=EInt 'during' duration=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'Rectangle' name=EString '->' hexadecimalValue=EString position=Position 'at' beginTime=EInt 'during' duration=EInt
		public Group getGroup() { return cGroup; }
		
		//'Rectangle'
		public Keyword getRectangleKeyword_0() { return cRectangleKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//hexadecimalValue=EString
		public Assignment getHexadecimalValueAssignment_3() { return cHexadecimalValueAssignment_3; }
		
		//EString
		public RuleCall getHexadecimalValueEStringParserRuleCall_3_0() { return cHexadecimalValueEStringParserRuleCall_3_0; }
		
		//position=Position
		public Assignment getPositionAssignment_4() { return cPositionAssignment_4; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_4_0() { return cPositionPositionParserRuleCall_4_0; }
		
		//'at'
		public Keyword getAtKeyword_5() { return cAtKeyword_5; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_6() { return cBeginTimeAssignment_6; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_6_0() { return cBeginTimeEIntParserRuleCall_6_0; }
		
		//'during'
		public Keyword getDuringKeyword_7() { return cDuringKeyword_7; }
		
		//duration=EInt
		public Assignment getDurationAssignment_8() { return cDurationAssignment_8; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_8_0() { return cDurationEIntParserRuleCall_8_0; }
	}
	
	
	private final MovieElements pMovie;
	private final ElementElements pElement;
	private final LayerElements pLayer;
	private final EStringElements pEString;
	private final PositionElements pPosition;
	private final EIntElements pEInt;
	private final TextElements pText;
	private final PictureElements pPicture;
	private final VideoElements pVideo;
	private final FadeInElements pFadeIn;
	private final FadeOutElements pFadeOut;
	private final TranslateElements pTranslate;
	private final RectangleElements pRectangle;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CinEditorGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMovie = new MovieElements();
		this.pElement = new ElementElements();
		this.pLayer = new LayerElements();
		this.pEString = new EStringElements();
		this.pPosition = new PositionElements();
		this.pEInt = new EIntElements();
		this.pText = new TextElements();
		this.pPicture = new PictureElements();
		this.pVideo = new VideoElements();
		this.pFadeIn = new FadeInElements();
		this.pFadeOut = new FadeOutElements();
		this.pTranslate = new TranslateElements();
		this.pRectangle = new RectangleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("polytech.spaceteam.cineditor.CinEditor".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Movie:
	//	'Movie' name=EString position=Position
	//	layers+=Layer+;
	public MovieElements getMovieAccess() {
		return pMovie;
	}
	
	public ParserRule getMovieRule() {
		return getMovieAccess().getRule();
	}
	
	//Element:
	//	Text | Picture | Video | FadeIn | FadeOut | Translate | Rectangle;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//Layer:
	//	{Layer}
	//	'Layer'
	//	elements+=Element+;
	public LayerElements getLayerAccess() {
		return pLayer;
	}
	
	public ParserRule getLayerRule() {
		return getLayerAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Position:
	//	'position' width=EInt 'x' height=EInt ('(' x=EInt ',' y=EInt ')')?;
	public PositionElements getPositionAccess() {
		return pPosition;
	}
	
	public ParserRule getPositionRule() {
		return getPositionAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Text:
	//	'Text' name=EString '->' text=EString position=Position 'at' beginTime=EInt 'during' duration=EInt;
	public TextElements getTextAccess() {
		return pText;
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}
	
	//Picture:
	//	'Picture' name=EString '->' '"' url=EString '"' position=Position 'at' beginTime=EInt 'during' duration=EInt;
	public PictureElements getPictureAccess() {
		return pPicture;
	}
	
	public ParserRule getPictureRule() {
		return getPictureAccess().getRule();
	}
	
	//Video:
	//	'Video' name=EString '->' '"' url=EString '"' 'from' beginCropTime=EInt position=Position 'at' beginTime=EInt
	//	'during' duration=EInt;
	public VideoElements getVideoAccess() {
		return pVideo;
	}
	
	public ParserRule getVideoRule() {
		return getVideoAccess().getRule();
	}
	
	//FadeIn:
	//	'Effect' name=EString '->' 'FadeIn' 'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element];
	public FadeInElements getFadeInAccess() {
		return pFadeIn;
	}
	
	public ParserRule getFadeInRule() {
		return getFadeInAccess().getRule();
	}
	
	//FadeOut:
	//	'Effect' name=EString '->' 'FadeOut' 'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element];
	public FadeOutElements getFadeOutAccess() {
		return pFadeOut;
	}
	
	public ParserRule getFadeOutRule() {
		return getFadeOutAccess().getRule();
	}
	
	//Translate:
	//	'Effect' name=EString '->' 'Translate' '(' pixelsToTranslateHorizontally=EInt ',' pixelsToTranslateVertically=EInt
	//	')' 'at' beginTime=EInt 'during' duration=EInt 'on' element=[Element];
	public TranslateElements getTranslateAccess() {
		return pTranslate;
	}
	
	public ParserRule getTranslateRule() {
		return getTranslateAccess().getRule();
	}
	
	//Rectangle:
	//	'Rectangle' name=EString '->' hexadecimalValue=EString position=Position 'at' beginTime=EInt 'during' duration=EInt;
	public RectangleElements getRectangleAccess() {
		return pRectangle;
	}
	
	public ParserRule getRectangleRule() {
		return getRectangleAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
