/*
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CinEditorGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MovieElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Movie");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMovieKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDimensionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDimensionDimensionParserRuleCall_2_0 = (RuleCall)cDimensionAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFpsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFpsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFpsEIntParserRuleCall_3_1_0 = (RuleCall)cFpsAssignment_3_1.eContents().get(0);
		private final Assignment cLayersAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLayersLayerParserRuleCall_4_0 = (RuleCall)cLayersAssignment_4.eContents().get(0);
		
		//Movie:
		//	'Movie' name=EString dimension=Dimension ('fps' fps=EInt)?
		//	layers+=Layer+;
		@Override public ParserRule getRule() { return rule; }
		
		//'Movie' name=EString dimension=Dimension ('fps' fps=EInt)? layers+=Layer+
		public Group getGroup() { return cGroup; }
		
		//'Movie'
		public Keyword getMovieKeyword_0() { return cMovieKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//dimension=Dimension
		public Assignment getDimensionAssignment_2() { return cDimensionAssignment_2; }
		
		//Dimension
		public RuleCall getDimensionDimensionParserRuleCall_2_0() { return cDimensionDimensionParserRuleCall_2_0; }
		
		//('fps' fps=EInt)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'fps'
		public Keyword getFpsKeyword_3_0() { return cFpsKeyword_3_0; }
		
		//fps=EInt
		public Assignment getFpsAssignment_3_1() { return cFpsAssignment_3_1; }
		
		//EInt
		public RuleCall getFpsEIntParserRuleCall_3_1_0() { return cFpsEIntParserRuleCall_3_1_0; }
		
		//layers+=Layer+
		public Assignment getLayersAssignment_4() { return cLayersAssignment_4; }
		
		//Layer
		public RuleCall getLayersLayerParserRuleCall_4_0() { return cLayersLayerParserRuleCall_4_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGraphicalElementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFadeInParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFadeOutParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cTranslateParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cAudioElementParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Element:
		//	GraphicalElement | FadeIn | FadeOut | Translate | AudioElement;
		@Override public ParserRule getRule() { return rule; }
		
		//GraphicalElement | FadeIn | FadeOut | Translate | AudioElement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//GraphicalElement
		public RuleCall getGraphicalElementParserRuleCall_0() { return cGraphicalElementParserRuleCall_0; }
		
		//FadeIn
		public RuleCall getFadeInParserRuleCall_1() { return cFadeInParserRuleCall_1; }
		
		//FadeOut
		public RuleCall getFadeOutParserRuleCall_2() { return cFadeOutParserRuleCall_2; }
		
		//Translate
		public RuleCall getTranslateParserRuleCall_3() { return cTranslateParserRuleCall_3; }
		
		//AudioElement
		public RuleCall getAudioElementParserRuleCall_4() { return cAudioElementParserRuleCall_4; }
	}
	public class LayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Layer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLayerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLayerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsElementParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		
		//Layer:
		//	{Layer}
		//	'Layer'
		//	elements+=Element+;
		@Override public ParserRule getRule() { return rule; }
		
		//{Layer} 'Layer' elements+=Element+
		public Group getGroup() { return cGroup; }
		
		//{Layer}
		public Action getLayerAction_0() { return cLayerAction_0; }
		
		//'Layer'
		public Keyword getLayerKeyword_1() { return cLayerKeyword_1; }
		
		//elements+=Element+
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }
		
		//Element
		public RuleCall getElementsElementParserRuleCall_2_0() { return cElementsElementParserRuleCall_2_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class PositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Position");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPositionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cXAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cXItemPositionParserRuleCall_1_1_0 = (RuleCall)cXAssignment_1_1.eContents().get(0);
		private final Keyword cCommaKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cYAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cYItemPositionParserRuleCall_1_3_0 = (RuleCall)cYAssignment_1_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		
		//Position:
		//	'position' ('(' x=ItemPosition ',' y=ItemPosition ')');
		@Override public ParserRule getRule() { return rule; }
		
		//'position' ('(' x=ItemPosition ',' y=ItemPosition ')')
		public Group getGroup() { return cGroup; }
		
		//'position'
		public Keyword getPositionKeyword_0() { return cPositionKeyword_0; }
		
		//'(' x=ItemPosition ',' y=ItemPosition ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//x=ItemPosition
		public Assignment getXAssignment_1_1() { return cXAssignment_1_1; }
		
		//ItemPosition
		public RuleCall getXItemPositionParserRuleCall_1_1_0() { return cXItemPositionParserRuleCall_1_1_0; }
		
		//','
		public Keyword getCommaKeyword_1_2() { return cCommaKeyword_1_2; }
		
		//y=ItemPosition
		public Assignment getYAssignment_1_3() { return cYAssignment_1_3; }
		
		//ItemPosition
		public RuleCall getYItemPositionParserRuleCall_1_3_0() { return cYItemPositionParserRuleCall_1_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_4() { return cRightParenthesisKeyword_1_4; }
	}
	public class ItemPositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.ItemPosition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cItemPositionIntParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cItemPositionStringParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ItemPosition:
		//	ItemPositionInt | ItemPositionString;
		@Override public ParserRule getRule() { return rule; }
		
		//ItemPositionInt | ItemPositionString
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ItemPositionInt
		public RuleCall getItemPositionIntParserRuleCall_0() { return cItemPositionIntParserRuleCall_0; }
		
		//ItemPositionString
		public RuleCall getItemPositionStringParserRuleCall_1() { return cItemPositionStringParserRuleCall_1; }
	}
	public class ItemPositionIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.ItemPositionInt");
		private final Assignment cPositionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPositionEIntParserRuleCall_0 = (RuleCall)cPositionAssignment.eContents().get(0);
		
		//ItemPositionInt:
		//	position=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//position=EInt
		public Assignment getPositionAssignment() { return cPositionAssignment; }
		
		//EInt
		public RuleCall getPositionEIntParserRuleCall_0() { return cPositionEIntParserRuleCall_0; }
	}
	public class ItemPositionStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.ItemPositionString");
		private final Assignment cPositionAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cPositionAlternatives_0 = (Alternatives)cPositionAssignment.eContents().get(0);
		private final Keyword cPositionCenterKeyword_0_0 = (Keyword)cPositionAlternatives_0.eContents().get(0);
		private final Keyword cPositionLeftKeyword_0_1 = (Keyword)cPositionAlternatives_0.eContents().get(1);
		private final Keyword cPositionRightKeyword_0_2 = (Keyword)cPositionAlternatives_0.eContents().get(2);
		private final Keyword cPositionBottomKeyword_0_3 = (Keyword)cPositionAlternatives_0.eContents().get(3);
		private final Keyword cPositionTopKeyword_0_4 = (Keyword)cPositionAlternatives_0.eContents().get(4);
		
		//ItemPositionString:
		//	position=('center' | 'left' | 'right' | 'bottom' | 'top');
		@Override public ParserRule getRule() { return rule; }
		
		//position=('center' | 'left' | 'right' | 'bottom' | 'top')
		public Assignment getPositionAssignment() { return cPositionAssignment; }
		
		//('center' | 'left' | 'right' | 'bottom' | 'top')
		public Alternatives getPositionAlternatives_0() { return cPositionAlternatives_0; }
		
		//'center'
		public Keyword getPositionCenterKeyword_0_0() { return cPositionCenterKeyword_0_0; }
		
		//'left'
		public Keyword getPositionLeftKeyword_0_1() { return cPositionLeftKeyword_0_1; }
		
		//'right'
		public Keyword getPositionRightKeyword_0_2() { return cPositionRightKeyword_0_2; }
		
		//'bottom'
		public Keyword getPositionBottomKeyword_0_3() { return cPositionBottomKeyword_0_3; }
		
		//'top'
		public Keyword getPositionTopKeyword_0_4() { return cPositionTopKeyword_0_4; }
	}
	public class DimensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Dimension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDimensionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cWidthAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cWidthEIntParserRuleCall_1_0 = (RuleCall)cWidthAssignment_1.eContents().get(0);
		private final Keyword cXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cHeightAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHeightEIntParserRuleCall_3_0 = (RuleCall)cHeightAssignment_3.eContents().get(0);
		
		//Dimension:
		//	'dimension' width=EInt 'x' height=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'dimension' width=EInt 'x' height=EInt
		public Group getGroup() { return cGroup; }
		
		//'dimension'
		public Keyword getDimensionKeyword_0() { return cDimensionKeyword_0; }
		
		//width=EInt
		public Assignment getWidthAssignment_1() { return cWidthAssignment_1; }
		
		//EInt
		public RuleCall getWidthEIntParserRuleCall_1_0() { return cWidthEIntParserRuleCall_1_0; }
		
		//'x'
		public Keyword getXKeyword_2() { return cXKeyword_2; }
		
		//height=EInt
		public Assignment getHeightAssignment_3() { return cHeightAssignment_3; }
		
		//EInt
		public RuleCall getHeightEIntParserRuleCall_3_0() { return cHeightEIntParserRuleCall_3_0; }
	}
	public class HexadecimalColorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.HexadecimalColor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHexadecimalValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHexadecimalValueEStringParserRuleCall_1_0 = (RuleCall)cHexadecimalValueAssignment_1.eContents().get(0);
		
		//HexadecimalColor:
		//	'color' hexadecimalValue=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'color' hexadecimalValue=EString
		public Group getGroup() { return cGroup; }
		
		//'color'
		public Keyword getColorKeyword_0() { return cColorKeyword_0; }
		
		//hexadecimalValue=EString
		public Assignment getHexadecimalValueAssignment_1() { return cHexadecimalValueAssignment_1; }
		
		//EString
		public RuleCall getHexadecimalValueEStringParserRuleCall_1_0() { return cHexadecimalValueEStringParserRuleCall_1_0; }
	}
	public class TemporalPositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.TemporalPosition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cStartAtKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cBeginTimeAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cBeginTimeEIntParserRuleCall_0_1_0 = (RuleCall)cBeginTimeAssignment_0_1.eContents().get(0);
		private final Keyword cStartAfterKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cElementToStartAfterAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final CrossReference cElementToStartAfterElementCrossReference_0_3_0 = (CrossReference)cElementToStartAfterAssignment_0_3.eContents().get(0);
		private final RuleCall cElementToStartAfterElementIDTerminalRuleCall_0_3_0_1 = (RuleCall)cElementToStartAfterElementCrossReference_0_3_0.eContents().get(1);
		private final Alternatives cAlternatives_1 = (Alternatives)cAlternatives.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cStartAtKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cBeginTimeAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cBeginTimeEIntParserRuleCall_1_0_1_0 = (RuleCall)cBeginTimeAssignment_1_0_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cStartAfterKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cElementToStartAfterAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final CrossReference cElementToStartAfterElementCrossReference_1_1_1_0 = (CrossReference)cElementToStartAfterAssignment_1_1_1.eContents().get(0);
		private final RuleCall cElementToStartAfterElementIDTerminalRuleCall_1_1_1_0_1 = (RuleCall)cElementToStartAfterElementCrossReference_1_1_1_0.eContents().get(1);
		
		//TemporalPosition:
		//	'startAt' beginTime=EInt 'startAfter' elementToStartAfter=[Element] | ('startAt' beginTime=EInt | 'startAfter'
		//	elementToStartAfter=[Element]);
		@Override public ParserRule getRule() { return rule; }
		
		//'startAt' beginTime=EInt 'startAfter' elementToStartAfter=[Element] | ('startAt' beginTime=EInt | 'startAfter'
		//elementToStartAfter=[Element])
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'startAt' beginTime=EInt 'startAfter' elementToStartAfter=[Element]
		public Group getGroup_0() { return cGroup_0; }
		
		//'startAt'
		public Keyword getStartAtKeyword_0_0() { return cStartAtKeyword_0_0; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_0_1() { return cBeginTimeAssignment_0_1; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_0_1_0() { return cBeginTimeEIntParserRuleCall_0_1_0; }
		
		//'startAfter'
		public Keyword getStartAfterKeyword_0_2() { return cStartAfterKeyword_0_2; }
		
		//elementToStartAfter=[Element]
		public Assignment getElementToStartAfterAssignment_0_3() { return cElementToStartAfterAssignment_0_3; }
		
		//[Element]
		public CrossReference getElementToStartAfterElementCrossReference_0_3_0() { return cElementToStartAfterElementCrossReference_0_3_0; }
		
		//ID
		public RuleCall getElementToStartAfterElementIDTerminalRuleCall_0_3_0_1() { return cElementToStartAfterElementIDTerminalRuleCall_0_3_0_1; }
		
		//('startAt' beginTime=EInt | 'startAfter' elementToStartAfter=[Element])
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'startAt' beginTime=EInt
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'startAt'
		public Keyword getStartAtKeyword_1_0_0() { return cStartAtKeyword_1_0_0; }
		
		//beginTime=EInt
		public Assignment getBeginTimeAssignment_1_0_1() { return cBeginTimeAssignment_1_0_1; }
		
		//EInt
		public RuleCall getBeginTimeEIntParserRuleCall_1_0_1_0() { return cBeginTimeEIntParserRuleCall_1_0_1_0; }
		
		//'startAfter' elementToStartAfter=[Element]
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'startAfter'
		public Keyword getStartAfterKeyword_1_1_0() { return cStartAfterKeyword_1_1_0; }
		
		//elementToStartAfter=[Element]
		public Assignment getElementToStartAfterAssignment_1_1_1() { return cElementToStartAfterAssignment_1_1_1; }
		
		//[Element]
		public CrossReference getElementToStartAfterElementCrossReference_1_1_1_0() { return cElementToStartAfterElementCrossReference_1_1_1_0; }
		
		//ID
		public RuleCall getElementToStartAfterElementIDTerminalRuleCall_1_1_1_0_1() { return cElementToStartAfterElementIDTerminalRuleCall_1_1_1_0_1; }
	}
	public class GraphicalElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.GraphicalElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTextParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVideoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPictureParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cRectangleParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//GraphicalElement:
		//	Text | Video | Picture | Rectangle;
		@Override public ParserRule getRule() { return rule; }
		
		//Text | Video | Picture | Rectangle
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Text
		public RuleCall getTextParserRuleCall_0() { return cTextParserRuleCall_0; }
		
		//Video
		public RuleCall getVideoParserRuleCall_1() { return cVideoParserRuleCall_1; }
		
		//Picture
		public RuleCall getPictureParserRuleCall_2() { return cPictureParserRuleCall_2; }
		
		//Rectangle
		public RuleCall getRectangleParserRuleCall_3() { return cRectangleParserRuleCall_3; }
	}
	public class MarginElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Margin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeMARGIN_NAMEEnumRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSizeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSizeEIntParserRuleCall_2_0 = (RuleCall)cSizeAssignment_2.eContents().get(0);
		private final Assignment cMarginColorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMarginColorHexadecimalColorParserRuleCall_3_0 = (RuleCall)cMarginColorAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOpacityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMarginColorOpacityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMarginColorOpacityEFloatParserRuleCall_4_1_0 = (RuleCall)cMarginColorOpacityAssignment_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Margin:
		//	type=MARGIN_NAME '(' size=EInt marginColor=HexadecimalColor? ('opacity' marginColorOpacity=EFloat)? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//type=MARGIN_NAME '(' size=EInt marginColor=HexadecimalColor? ('opacity' marginColorOpacity=EFloat)? ')'
		public Group getGroup() { return cGroup; }
		
		//type=MARGIN_NAME
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//MARGIN_NAME
		public RuleCall getTypeMARGIN_NAMEEnumRuleCall_0_0() { return cTypeMARGIN_NAMEEnumRuleCall_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//size=EInt
		public Assignment getSizeAssignment_2() { return cSizeAssignment_2; }
		
		//EInt
		public RuleCall getSizeEIntParserRuleCall_2_0() { return cSizeEIntParserRuleCall_2_0; }
		
		//marginColor=HexadecimalColor?
		public Assignment getMarginColorAssignment_3() { return cMarginColorAssignment_3; }
		
		//HexadecimalColor
		public RuleCall getMarginColorHexadecimalColorParserRuleCall_3_0() { return cMarginColorHexadecimalColorParserRuleCall_3_0; }
		
		//('opacity' marginColorOpacity=EFloat)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'opacity'
		public Keyword getOpacityKeyword_4_0() { return cOpacityKeyword_4_0; }
		
		//marginColorOpacity=EFloat
		public Assignment getMarginColorOpacityAssignment_4_1() { return cMarginColorOpacityAssignment_4_1; }
		
		//EFloat
		public RuleCall getMarginColorOpacityEFloatParserRuleCall_4_1_0() { return cMarginColorOpacityEFloatParserRuleCall_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_2_0 = (Alternatives)cGroup_2.eContents().get(0);
		private final Keyword cFullStopKeyword_2_0_0 = (Keyword)cAlternatives_2_0.eContents().get(0);
		private final Keyword cCommaKeyword_2_0_1 = (Keyword)cAlternatives_2_0.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		
		//EFloat ecore::EFloat:
		//	'-'? INT (('.' | ',') INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT (('.' | ',') INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//(('.' | ',') INT)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'.' | ','
		public Alternatives getAlternatives_2_0() { return cAlternatives_2_0; }
		
		//'.'
		public Keyword getFullStopKeyword_2_0_0() { return cFullStopKeyword_2_0_0; }
		
		//','
		public Keyword getCommaKeyword_2_0_1() { return cCommaKeyword_2_0_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2_1() { return cINTTerminalRuleCall_2_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class AudioElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.AudioElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAudioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUrlAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUrlEStringParserRuleCall_3_0 = (RuleCall)cUrlAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVolumeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVolumeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVolumeEFloatParserRuleCall_4_1_0 = (RuleCall)cVolumeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cFadeInKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cFadeInAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cFadeInEIntParserRuleCall_5_1_0 = (RuleCall)cFadeInAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cFadeOutKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cFadeOutAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cFadeOutEIntParserRuleCall_6_1_0 = (RuleCall)cFadeOutAssignment_6_1.eContents().get(0);
		private final Assignment cTemporalPositionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTemporalPositionTemporalPositionParserRuleCall_7_0 = (RuleCall)cTemporalPositionAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCropAtKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cBeginCropTimeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cBeginCropTimeEIntParserRuleCall_8_1_0 = (RuleCall)cBeginCropTimeAssignment_8_1.eContents().get(0);
		private final Keyword cDuringKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDurationAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDurationEIntParserRuleCall_10_0 = (RuleCall)cDurationAssignment_10.eContents().get(0);
		
		//AudioElement:
		//	'Audio' name=EString '=' url=EString ('volume' volume=EFloat)? ('fadeIn' fadeIn=EInt)? ('fadeOut' fadeOut=EInt)?
		//	temporalPosition=TemporalPosition? ('cropAt' beginCropTime=EInt)? 'during' duration=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'Audio' name=EString '=' url=EString ('volume' volume=EFloat)? ('fadeIn' fadeIn=EInt)? ('fadeOut' fadeOut=EInt)?
		//temporalPosition=TemporalPosition? ('cropAt' beginCropTime=EInt)? 'during' duration=EInt
		public Group getGroup() { return cGroup; }
		
		//'Audio'
		public Keyword getAudioKeyword_0() { return cAudioKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//url=EString
		public Assignment getUrlAssignment_3() { return cUrlAssignment_3; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_0() { return cUrlEStringParserRuleCall_3_0; }
		
		//('volume' volume=EFloat)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'volume'
		public Keyword getVolumeKeyword_4_0() { return cVolumeKeyword_4_0; }
		
		//volume=EFloat
		public Assignment getVolumeAssignment_4_1() { return cVolumeAssignment_4_1; }
		
		//EFloat
		public RuleCall getVolumeEFloatParserRuleCall_4_1_0() { return cVolumeEFloatParserRuleCall_4_1_0; }
		
		//('fadeIn' fadeIn=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'fadeIn'
		public Keyword getFadeInKeyword_5_0() { return cFadeInKeyword_5_0; }
		
		//fadeIn=EInt
		public Assignment getFadeInAssignment_5_1() { return cFadeInAssignment_5_1; }
		
		//EInt
		public RuleCall getFadeInEIntParserRuleCall_5_1_0() { return cFadeInEIntParserRuleCall_5_1_0; }
		
		//('fadeOut' fadeOut=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'fadeOut'
		public Keyword getFadeOutKeyword_6_0() { return cFadeOutKeyword_6_0; }
		
		//fadeOut=EInt
		public Assignment getFadeOutAssignment_6_1() { return cFadeOutAssignment_6_1; }
		
		//EInt
		public RuleCall getFadeOutEIntParserRuleCall_6_1_0() { return cFadeOutEIntParserRuleCall_6_1_0; }
		
		//temporalPosition=TemporalPosition?
		public Assignment getTemporalPositionAssignment_7() { return cTemporalPositionAssignment_7; }
		
		//TemporalPosition
		public RuleCall getTemporalPositionTemporalPositionParserRuleCall_7_0() { return cTemporalPositionTemporalPositionParserRuleCall_7_0; }
		
		//('cropAt' beginCropTime=EInt)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'cropAt'
		public Keyword getCropAtKeyword_8_0() { return cCropAtKeyword_8_0; }
		
		//beginCropTime=EInt
		public Assignment getBeginCropTimeAssignment_8_1() { return cBeginCropTimeAssignment_8_1; }
		
		//EInt
		public RuleCall getBeginCropTimeEIntParserRuleCall_8_1_0() { return cBeginCropTimeEIntParserRuleCall_8_1_0; }
		
		//'during'
		public Keyword getDuringKeyword_9() { return cDuringKeyword_9; }
		
		//duration=EInt
		public Assignment getDurationAssignment_10() { return cDurationAssignment_10; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_10_0() { return cDurationEIntParserRuleCall_10_0; }
	}
	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Text");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTextEStringParserRuleCall_3_0 = (RuleCall)cTextAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFontSizeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFontSizeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFontSizeEIntParserRuleCall_4_1_0 = (RuleCall)cFontSizeAssignment_4_1.eContents().get(0);
		private final Assignment cPositionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPositionPositionParserRuleCall_5_0 = (RuleCall)cPositionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMarginsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMarginsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMarginsMarginParserRuleCall_6_1_0 = (RuleCall)cMarginsAssignment_6_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Assignment cTemporalPositionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTemporalPositionTemporalPositionParserRuleCall_7_0 = (RuleCall)cTemporalPositionAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDuringKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDurationAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cDurationEIntParserRuleCall_8_1_0 = (RuleCall)cDurationAssignment_8_1.eContents().get(0);
		private final Assignment cColorAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cColorHexadecimalColorParserRuleCall_9_0 = (RuleCall)cColorAssignment_9.eContents().get(0);
		
		//Text:
		//	'Text' name=EString '=' text=EString ('fontSize' fontSize=EInt)? position=Position? ('margins(' margins+=Margin+
		//	')')? temporalPosition=TemporalPosition? ('during' duration=EInt)? color=HexadecimalColor;
		@Override public ParserRule getRule() { return rule; }
		
		//'Text' name=EString '=' text=EString ('fontSize' fontSize=EInt)? position=Position? ('margins(' margins+=Margin+ ')')?
		//temporalPosition=TemporalPosition? ('during' duration=EInt)? color=HexadecimalColor
		public Group getGroup() { return cGroup; }
		
		//'Text'
		public Keyword getTextKeyword_0() { return cTextKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//text=EString
		public Assignment getTextAssignment_3() { return cTextAssignment_3; }
		
		//EString
		public RuleCall getTextEStringParserRuleCall_3_0() { return cTextEStringParserRuleCall_3_0; }
		
		//('fontSize' fontSize=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'fontSize'
		public Keyword getFontSizeKeyword_4_0() { return cFontSizeKeyword_4_0; }
		
		//fontSize=EInt
		public Assignment getFontSizeAssignment_4_1() { return cFontSizeAssignment_4_1; }
		
		//EInt
		public RuleCall getFontSizeEIntParserRuleCall_4_1_0() { return cFontSizeEIntParserRuleCall_4_1_0; }
		
		//position=Position?
		public Assignment getPositionAssignment_5() { return cPositionAssignment_5; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_5_0() { return cPositionPositionParserRuleCall_5_0; }
		
		//('margins(' margins+=Margin+ ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'margins('
		public Keyword getMarginsKeyword_6_0() { return cMarginsKeyword_6_0; }
		
		//margins+=Margin+
		public Assignment getMarginsAssignment_6_1() { return cMarginsAssignment_6_1; }
		
		//Margin
		public RuleCall getMarginsMarginParserRuleCall_6_1_0() { return cMarginsMarginParserRuleCall_6_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_2() { return cRightParenthesisKeyword_6_2; }
		
		//temporalPosition=TemporalPosition?
		public Assignment getTemporalPositionAssignment_7() { return cTemporalPositionAssignment_7; }
		
		//TemporalPosition
		public RuleCall getTemporalPositionTemporalPositionParserRuleCall_7_0() { return cTemporalPositionTemporalPositionParserRuleCall_7_0; }
		
		//('during' duration=EInt)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'during'
		public Keyword getDuringKeyword_8_0() { return cDuringKeyword_8_0; }
		
		//duration=EInt
		public Assignment getDurationAssignment_8_1() { return cDurationAssignment_8_1; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_8_1_0() { return cDurationEIntParserRuleCall_8_1_0; }
		
		//color=HexadecimalColor
		public Assignment getColorAssignment_9() { return cColorAssignment_9; }
		
		//HexadecimalColor
		public RuleCall getColorHexadecimalColorParserRuleCall_9_0() { return cColorHexadecimalColorParserRuleCall_9_0; }
	}
	public class PictureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Picture");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPictureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUrlAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUrlEStringParserRuleCall_3_0 = (RuleCall)cUrlAssignment_3.eContents().get(0);
		private final Assignment cPositionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPositionPositionParserRuleCall_4_0 = (RuleCall)cPositionAssignment_4.eContents().get(0);
		private final Assignment cDimensionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDimensionDimensionParserRuleCall_5_0 = (RuleCall)cDimensionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMarginsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMarginsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMarginsMarginParserRuleCall_6_1_0 = (RuleCall)cMarginsAssignment_6_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Assignment cTemporalPositionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTemporalPositionTemporalPositionParserRuleCall_7_0 = (RuleCall)cTemporalPositionAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDuringKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDurationAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cDurationEIntParserRuleCall_8_1_0 = (RuleCall)cDurationAssignment_8_1.eContents().get(0);
		
		//Picture:
		//	'Picture' name=EString '=' url=EString position=Position? dimension=Dimension? ('margins(' margins+=Margin+ ')')?
		//	temporalPosition=TemporalPosition? ('during' duration=EInt)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Picture' name=EString '=' url=EString position=Position? dimension=Dimension? ('margins(' margins+=Margin+ ')')?
		//temporalPosition=TemporalPosition? ('during' duration=EInt)?
		public Group getGroup() { return cGroup; }
		
		//'Picture'
		public Keyword getPictureKeyword_0() { return cPictureKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//url=EString
		public Assignment getUrlAssignment_3() { return cUrlAssignment_3; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_0() { return cUrlEStringParserRuleCall_3_0; }
		
		//position=Position?
		public Assignment getPositionAssignment_4() { return cPositionAssignment_4; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_4_0() { return cPositionPositionParserRuleCall_4_0; }
		
		//dimension=Dimension?
		public Assignment getDimensionAssignment_5() { return cDimensionAssignment_5; }
		
		//Dimension
		public RuleCall getDimensionDimensionParserRuleCall_5_0() { return cDimensionDimensionParserRuleCall_5_0; }
		
		//('margins(' margins+=Margin+ ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'margins('
		public Keyword getMarginsKeyword_6_0() { return cMarginsKeyword_6_0; }
		
		//margins+=Margin+
		public Assignment getMarginsAssignment_6_1() { return cMarginsAssignment_6_1; }
		
		//Margin
		public RuleCall getMarginsMarginParserRuleCall_6_1_0() { return cMarginsMarginParserRuleCall_6_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_2() { return cRightParenthesisKeyword_6_2; }
		
		//temporalPosition=TemporalPosition?
		public Assignment getTemporalPositionAssignment_7() { return cTemporalPositionAssignment_7; }
		
		//TemporalPosition
		public RuleCall getTemporalPositionTemporalPositionParserRuleCall_7_0() { return cTemporalPositionTemporalPositionParserRuleCall_7_0; }
		
		//('during' duration=EInt)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'during'
		public Keyword getDuringKeyword_8_0() { return cDuringKeyword_8_0; }
		
		//duration=EInt
		public Assignment getDurationAssignment_8_1() { return cDurationAssignment_8_1; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_8_1_0() { return cDurationEIntParserRuleCall_8_1_0; }
	}
	public class VideoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Video");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVideoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUrlAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUrlEStringParserRuleCall_3_0 = (RuleCall)cUrlAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAudioKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cEnableAudioAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cEnableAudioEBooleanParserRuleCall_4_1_0 = (RuleCall)cEnableAudioAssignment_4_1.eContents().get(0);
		private final Assignment cPositionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPositionPositionParserRuleCall_5_0 = (RuleCall)cPositionAssignment_5.eContents().get(0);
		private final Assignment cDimensionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cDimensionDimensionParserRuleCall_6_0 = (RuleCall)cDimensionAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMarginsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMarginsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMarginsMarginParserRuleCall_7_1_0 = (RuleCall)cMarginsAssignment_7_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Assignment cTemporalPositionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTemporalPositionTemporalPositionParserRuleCall_8_0 = (RuleCall)cTemporalPositionAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCropAtKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cBeginCropTimeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cBeginCropTimeEIntParserRuleCall_9_1_0 = (RuleCall)cBeginCropTimeAssignment_9_1.eContents().get(0);
		private final Keyword cDuringKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cDurationAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cDurationEIntParserRuleCall_11_0 = (RuleCall)cDurationAssignment_11.eContents().get(0);
		
		//Video:
		//	'Video' name=EString '=' url=EString ('audio' enableAudio=EBoolean)? position=Position? dimension=Dimension?
		//	('margins(' margins+=Margin+ ')')? temporalPosition=TemporalPosition? ('cropAt' beginCropTime=EInt)? 'during'
		//	duration=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'Video' name=EString '=' url=EString ('audio' enableAudio=EBoolean)? position=Position? dimension=Dimension? ('margins('
		//margins+=Margin+ ')')? temporalPosition=TemporalPosition? ('cropAt' beginCropTime=EInt)? 'during' duration=EInt
		public Group getGroup() { return cGroup; }
		
		//'Video'
		public Keyword getVideoKeyword_0() { return cVideoKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//url=EString
		public Assignment getUrlAssignment_3() { return cUrlAssignment_3; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_0() { return cUrlEStringParserRuleCall_3_0; }
		
		//('audio' enableAudio=EBoolean)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'audio'
		public Keyword getAudioKeyword_4_0() { return cAudioKeyword_4_0; }
		
		//enableAudio=EBoolean
		public Assignment getEnableAudioAssignment_4_1() { return cEnableAudioAssignment_4_1; }
		
		//EBoolean
		public RuleCall getEnableAudioEBooleanParserRuleCall_4_1_0() { return cEnableAudioEBooleanParserRuleCall_4_1_0; }
		
		//position=Position?
		public Assignment getPositionAssignment_5() { return cPositionAssignment_5; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_5_0() { return cPositionPositionParserRuleCall_5_0; }
		
		//dimension=Dimension?
		public Assignment getDimensionAssignment_6() { return cDimensionAssignment_6; }
		
		//Dimension
		public RuleCall getDimensionDimensionParserRuleCall_6_0() { return cDimensionDimensionParserRuleCall_6_0; }
		
		//('margins(' margins+=Margin+ ')')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'margins('
		public Keyword getMarginsKeyword_7_0() { return cMarginsKeyword_7_0; }
		
		//margins+=Margin+
		public Assignment getMarginsAssignment_7_1() { return cMarginsAssignment_7_1; }
		
		//Margin
		public RuleCall getMarginsMarginParserRuleCall_7_1_0() { return cMarginsMarginParserRuleCall_7_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_2() { return cRightParenthesisKeyword_7_2; }
		
		//temporalPosition=TemporalPosition?
		public Assignment getTemporalPositionAssignment_8() { return cTemporalPositionAssignment_8; }
		
		//TemporalPosition
		public RuleCall getTemporalPositionTemporalPositionParserRuleCall_8_0() { return cTemporalPositionTemporalPositionParserRuleCall_8_0; }
		
		//('cropAt' beginCropTime=EInt)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'cropAt'
		public Keyword getCropAtKeyword_9_0() { return cCropAtKeyword_9_0; }
		
		//beginCropTime=EInt
		public Assignment getBeginCropTimeAssignment_9_1() { return cBeginCropTimeAssignment_9_1; }
		
		//EInt
		public RuleCall getBeginCropTimeEIntParserRuleCall_9_1_0() { return cBeginCropTimeEIntParserRuleCall_9_1_0; }
		
		//'during'
		public Keyword getDuringKeyword_10() { return cDuringKeyword_10; }
		
		//duration=EInt
		public Assignment getDurationAssignment_11() { return cDurationAssignment_11; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_11_0() { return cDurationEIntParserRuleCall_11_0; }
	}
	public class RectangleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Rectangle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRectangleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cColorHexadecimalColorParserRuleCall_3_0 = (RuleCall)cColorAssignment_3.eContents().get(0);
		private final Assignment cPositionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPositionPositionParserRuleCall_4_0 = (RuleCall)cPositionAssignment_4.eContents().get(0);
		private final Assignment cDimensionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDimensionDimensionParserRuleCall_5_0 = (RuleCall)cDimensionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMarginsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMarginsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMarginsMarginParserRuleCall_6_1_0 = (RuleCall)cMarginsAssignment_6_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Assignment cTemporalPositionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTemporalPositionTemporalPositionParserRuleCall_7_0 = (RuleCall)cTemporalPositionAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDuringKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDurationAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cDurationEIntParserRuleCall_8_1_0 = (RuleCall)cDurationAssignment_8_1.eContents().get(0);
		
		//Rectangle:
		//	'Rectangle' name=EString '=' color=HexadecimalColor position=Position? dimension=Dimension? ('margins('
		//	margins+=Margin+ ')')? temporalPosition=TemporalPosition? ('during' duration=EInt)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Rectangle' name=EString '=' color=HexadecimalColor position=Position? dimension=Dimension? ('margins(' margins+=Margin+
		//')')? temporalPosition=TemporalPosition? ('during' duration=EInt)?
		public Group getGroup() { return cGroup; }
		
		//'Rectangle'
		public Keyword getRectangleKeyword_0() { return cRectangleKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//color=HexadecimalColor
		public Assignment getColorAssignment_3() { return cColorAssignment_3; }
		
		//HexadecimalColor
		public RuleCall getColorHexadecimalColorParserRuleCall_3_0() { return cColorHexadecimalColorParserRuleCall_3_0; }
		
		//position=Position?
		public Assignment getPositionAssignment_4() { return cPositionAssignment_4; }
		
		//Position
		public RuleCall getPositionPositionParserRuleCall_4_0() { return cPositionPositionParserRuleCall_4_0; }
		
		//dimension=Dimension?
		public Assignment getDimensionAssignment_5() { return cDimensionAssignment_5; }
		
		//Dimension
		public RuleCall getDimensionDimensionParserRuleCall_5_0() { return cDimensionDimensionParserRuleCall_5_0; }
		
		//('margins(' margins+=Margin+ ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'margins('
		public Keyword getMarginsKeyword_6_0() { return cMarginsKeyword_6_0; }
		
		//margins+=Margin+
		public Assignment getMarginsAssignment_6_1() { return cMarginsAssignment_6_1; }
		
		//Margin
		public RuleCall getMarginsMarginParserRuleCall_6_1_0() { return cMarginsMarginParserRuleCall_6_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_2() { return cRightParenthesisKeyword_6_2; }
		
		//temporalPosition=TemporalPosition?
		public Assignment getTemporalPositionAssignment_7() { return cTemporalPositionAssignment_7; }
		
		//TemporalPosition
		public RuleCall getTemporalPositionTemporalPositionParserRuleCall_7_0() { return cTemporalPositionTemporalPositionParserRuleCall_7_0; }
		
		//('during' duration=EInt)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'during'
		public Keyword getDuringKeyword_8_0() { return cDuringKeyword_8_0; }
		
		//duration=EInt
		public Assignment getDurationAssignment_8_1() { return cDurationAssignment_8_1; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_8_1_0() { return cDurationEIntParserRuleCall_8_1_0; }
	}
	public class FadeInElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.FadeIn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFadeInKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cDuringKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDurationAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDurationEIntParserRuleCall_5_0 = (RuleCall)cDurationAssignment_5.eContents().get(0);
		private final Keyword cOnKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cElementsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cElementsGraphicalElementCrossReference_8_0 = (CrossReference)cElementsAssignment_8.eContents().get(0);
		private final RuleCall cElementsGraphicalElementIDTerminalRuleCall_8_0_1 = (RuleCall)cElementsGraphicalElementCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cElementsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cElementsGraphicalElementCrossReference_9_1_0 = (CrossReference)cElementsAssignment_9_1.eContents().get(0);
		private final RuleCall cElementsGraphicalElementIDTerminalRuleCall_9_1_0_1 = (RuleCall)cElementsGraphicalElementCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//FadeIn:
		//	'Effect' name=EString '=' 'FadeIn' 'during' duration=EInt 'on' '[' elements+=[GraphicalElement] (','
		//	elements+=[GraphicalElement])* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'Effect' name=EString '=' 'FadeIn' 'during' duration=EInt 'on' '[' elements+=[GraphicalElement] (','
		//elements+=[GraphicalElement])* ']'
		public Group getGroup() { return cGroup; }
		
		//'Effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//'FadeIn'
		public Keyword getFadeInKeyword_3() { return cFadeInKeyword_3; }
		
		//'during'
		public Keyword getDuringKeyword_4() { return cDuringKeyword_4; }
		
		//duration=EInt
		public Assignment getDurationAssignment_5() { return cDurationAssignment_5; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_5_0() { return cDurationEIntParserRuleCall_5_0; }
		
		//'on'
		public Keyword getOnKeyword_6() { return cOnKeyword_6; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_7() { return cLeftSquareBracketKeyword_7; }
		
		//elements+=[GraphicalElement]
		public Assignment getElementsAssignment_8() { return cElementsAssignment_8; }
		
		//[GraphicalElement]
		public CrossReference getElementsGraphicalElementCrossReference_8_0() { return cElementsGraphicalElementCrossReference_8_0; }
		
		//ID
		public RuleCall getElementsGraphicalElementIDTerminalRuleCall_8_0_1() { return cElementsGraphicalElementIDTerminalRuleCall_8_0_1; }
		
		//(',' elements+=[GraphicalElement])*
		public Group getGroup_9() { return cGroup_9; }
		
		//','
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }
		
		//elements+=[GraphicalElement]
		public Assignment getElementsAssignment_9_1() { return cElementsAssignment_9_1; }
		
		//[GraphicalElement]
		public CrossReference getElementsGraphicalElementCrossReference_9_1_0() { return cElementsGraphicalElementCrossReference_9_1_0; }
		
		//ID
		public RuleCall getElementsGraphicalElementIDTerminalRuleCall_9_1_0_1() { return cElementsGraphicalElementIDTerminalRuleCall_9_1_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
	}
	public class FadeOutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.FadeOut");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFadeOutKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cDuringKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDurationAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDurationEIntParserRuleCall_5_0 = (RuleCall)cDurationAssignment_5.eContents().get(0);
		private final Keyword cOnKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cElementsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cElementsGraphicalElementCrossReference_8_0 = (CrossReference)cElementsAssignment_8.eContents().get(0);
		private final RuleCall cElementsGraphicalElementIDTerminalRuleCall_8_0_1 = (RuleCall)cElementsGraphicalElementCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cElementsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cElementsGraphicalElementCrossReference_9_1_0 = (CrossReference)cElementsAssignment_9_1.eContents().get(0);
		private final RuleCall cElementsGraphicalElementIDTerminalRuleCall_9_1_0_1 = (RuleCall)cElementsGraphicalElementCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//FadeOut:
		//	'Effect' name=EString '=' 'FadeOut' 'during' duration=EInt 'on' '[' elements+=[GraphicalElement] (','
		//	elements+=[GraphicalElement])* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'Effect' name=EString '=' 'FadeOut' 'during' duration=EInt 'on' '[' elements+=[GraphicalElement] (','
		//elements+=[GraphicalElement])* ']'
		public Group getGroup() { return cGroup; }
		
		//'Effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//'FadeOut'
		public Keyword getFadeOutKeyword_3() { return cFadeOutKeyword_3; }
		
		//'during'
		public Keyword getDuringKeyword_4() { return cDuringKeyword_4; }
		
		//duration=EInt
		public Assignment getDurationAssignment_5() { return cDurationAssignment_5; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_5_0() { return cDurationEIntParserRuleCall_5_0; }
		
		//'on'
		public Keyword getOnKeyword_6() { return cOnKeyword_6; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_7() { return cLeftSquareBracketKeyword_7; }
		
		//elements+=[GraphicalElement]
		public Assignment getElementsAssignment_8() { return cElementsAssignment_8; }
		
		//[GraphicalElement]
		public CrossReference getElementsGraphicalElementCrossReference_8_0() { return cElementsGraphicalElementCrossReference_8_0; }
		
		//ID
		public RuleCall getElementsGraphicalElementIDTerminalRuleCall_8_0_1() { return cElementsGraphicalElementIDTerminalRuleCall_8_0_1; }
		
		//(',' elements+=[GraphicalElement])*
		public Group getGroup_9() { return cGroup_9; }
		
		//','
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }
		
		//elements+=[GraphicalElement]
		public Assignment getElementsAssignment_9_1() { return cElementsAssignment_9_1; }
		
		//[GraphicalElement]
		public CrossReference getElementsGraphicalElementCrossReference_9_1_0() { return cElementsGraphicalElementCrossReference_9_1_0; }
		
		//ID
		public RuleCall getElementsGraphicalElementIDTerminalRuleCall_9_1_0_1() { return cElementsGraphicalElementIDTerminalRuleCall_9_1_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
	}
	public class TranslateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.Translate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTranslateKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPositionToTranslateAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPositionToTranslatePositionParserRuleCall_4_0 = (RuleCall)cPositionToTranslateAssignment_4.eContents().get(0);
		private final Assignment cTemporalPositionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTemporalPositionTemporalPositionParserRuleCall_5_0 = (RuleCall)cTemporalPositionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDuringKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDurationAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDurationEIntParserRuleCall_6_1_0 = (RuleCall)cDurationAssignment_6_1.eContents().get(0);
		private final Keyword cOnKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cElementsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cElementsGraphicalElementCrossReference_9_0 = (CrossReference)cElementsAssignment_9.eContents().get(0);
		private final RuleCall cElementsGraphicalElementIDTerminalRuleCall_9_0_1 = (RuleCall)cElementsGraphicalElementCrossReference_9_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cElementsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cElementsGraphicalElementCrossReference_10_1_0 = (CrossReference)cElementsAssignment_10_1.eContents().get(0);
		private final RuleCall cElementsGraphicalElementIDTerminalRuleCall_10_1_0_1 = (RuleCall)cElementsGraphicalElementCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Translate:
		//	'Effect' name=EString '=' 'Translate' positionToTranslate=Position temporalPosition=TemporalPosition? ('during'
		//	duration=EInt)? 'on' '[' elements+=[GraphicalElement] (',' elements+=[GraphicalElement])* ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'Effect' name=EString '=' 'Translate' positionToTranslate=Position temporalPosition=TemporalPosition? ('during'
		//duration=EInt)? 'on' '[' elements+=[GraphicalElement] (',' elements+=[GraphicalElement])* ']'
		public Group getGroup() { return cGroup; }
		
		//'Effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//'Translate'
		public Keyword getTranslateKeyword_3() { return cTranslateKeyword_3; }
		
		//positionToTranslate=Position
		public Assignment getPositionToTranslateAssignment_4() { return cPositionToTranslateAssignment_4; }
		
		//Position
		public RuleCall getPositionToTranslatePositionParserRuleCall_4_0() { return cPositionToTranslatePositionParserRuleCall_4_0; }
		
		//temporalPosition=TemporalPosition?
		public Assignment getTemporalPositionAssignment_5() { return cTemporalPositionAssignment_5; }
		
		//TemporalPosition
		public RuleCall getTemporalPositionTemporalPositionParserRuleCall_5_0() { return cTemporalPositionTemporalPositionParserRuleCall_5_0; }
		
		//('during' duration=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'during'
		public Keyword getDuringKeyword_6_0() { return cDuringKeyword_6_0; }
		
		//duration=EInt
		public Assignment getDurationAssignment_6_1() { return cDurationAssignment_6_1; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_6_1_0() { return cDurationEIntParserRuleCall_6_1_0; }
		
		//'on'
		public Keyword getOnKeyword_7() { return cOnKeyword_7; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_8() { return cLeftSquareBracketKeyword_8; }
		
		//elements+=[GraphicalElement]
		public Assignment getElementsAssignment_9() { return cElementsAssignment_9; }
		
		//[GraphicalElement]
		public CrossReference getElementsGraphicalElementCrossReference_9_0() { return cElementsGraphicalElementCrossReference_9_0; }
		
		//ID
		public RuleCall getElementsGraphicalElementIDTerminalRuleCall_9_0_1() { return cElementsGraphicalElementIDTerminalRuleCall_9_0_1; }
		
		//(',' elements+=[GraphicalElement])*
		public Group getGroup_10() { return cGroup_10; }
		
		//','
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//elements+=[GraphicalElement]
		public Assignment getElementsAssignment_10_1() { return cElementsAssignment_10_1; }
		
		//[GraphicalElement]
		public CrossReference getElementsGraphicalElementCrossReference_10_1_0() { return cElementsGraphicalElementCrossReference_10_1_0; }
		
		//ID
		public RuleCall getElementsGraphicalElementIDTerminalRuleCall_10_1_0_1() { return cElementsGraphicalElementIDTerminalRuleCall_10_1_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_11() { return cRightSquareBracketKeyword_11; }
	}
	
	public class MARGIN_NAMEElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "polytech.spaceteam.cineditor.CinEditor.MARGIN_NAME");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBOTTOMEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBOTTOMBottomKeyword_0_0 = (Keyword)cBOTTOMEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLEFTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLEFTLeftKeyword_1_0 = (Keyword)cLEFTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRIGHTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRIGHTRightKeyword_2_0 = (Keyword)cRIGHTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cTOPEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cTOPTopKeyword_3_0 = (Keyword)cTOPEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum MARGIN_NAME:
		//	BOTTOM='bottom' | LEFT='left' | RIGHT='right' | TOP='top';
		public EnumRule getRule() { return rule; }
		
		//BOTTOM='bottom' | LEFT='left' | RIGHT='right' | TOP='top'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BOTTOM='bottom'
		public EnumLiteralDeclaration getBOTTOMEnumLiteralDeclaration_0() { return cBOTTOMEnumLiteralDeclaration_0; }
		
		//'bottom'
		public Keyword getBOTTOMBottomKeyword_0_0() { return cBOTTOMBottomKeyword_0_0; }
		
		//LEFT='left'
		public EnumLiteralDeclaration getLEFTEnumLiteralDeclaration_1() { return cLEFTEnumLiteralDeclaration_1; }
		
		//'left'
		public Keyword getLEFTLeftKeyword_1_0() { return cLEFTLeftKeyword_1_0; }
		
		//RIGHT='right'
		public EnumLiteralDeclaration getRIGHTEnumLiteralDeclaration_2() { return cRIGHTEnumLiteralDeclaration_2; }
		
		//'right'
		public Keyword getRIGHTRightKeyword_2_0() { return cRIGHTRightKeyword_2_0; }
		
		//TOP='top'
		public EnumLiteralDeclaration getTOPEnumLiteralDeclaration_3() { return cTOPEnumLiteralDeclaration_3; }
		
		//'top'
		public Keyword getTOPTopKeyword_3_0() { return cTOPTopKeyword_3_0; }
	}
	
	private final MovieElements pMovie;
	private final ElementElements pElement;
	private final LayerElements pLayer;
	private final EStringElements pEString;
	private final PositionElements pPosition;
	private final ItemPositionElements pItemPosition;
	private final ItemPositionIntElements pItemPositionInt;
	private final ItemPositionStringElements pItemPositionString;
	private final DimensionElements pDimension;
	private final HexadecimalColorElements pHexadecimalColor;
	private final TemporalPositionElements pTemporalPosition;
	private final GraphicalElementElements pGraphicalElement;
	private final MarginElements pMargin;
	private final MARGIN_NAMEElements eMARGIN_NAME;
	private final EIntElements pEInt;
	private final EFloatElements pEFloat;
	private final EBooleanElements pEBoolean;
	private final AudioElementElements pAudioElement;
	private final TextElements pText;
	private final PictureElements pPicture;
	private final VideoElements pVideo;
	private final RectangleElements pRectangle;
	private final FadeInElements pFadeIn;
	private final FadeOutElements pFadeOut;
	private final TranslateElements pTranslate;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CinEditorGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMovie = new MovieElements();
		this.pElement = new ElementElements();
		this.pLayer = new LayerElements();
		this.pEString = new EStringElements();
		this.pPosition = new PositionElements();
		this.pItemPosition = new ItemPositionElements();
		this.pItemPositionInt = new ItemPositionIntElements();
		this.pItemPositionString = new ItemPositionStringElements();
		this.pDimension = new DimensionElements();
		this.pHexadecimalColor = new HexadecimalColorElements();
		this.pTemporalPosition = new TemporalPositionElements();
		this.pGraphicalElement = new GraphicalElementElements();
		this.pMargin = new MarginElements();
		this.eMARGIN_NAME = new MARGIN_NAMEElements();
		this.pEInt = new EIntElements();
		this.pEFloat = new EFloatElements();
		this.pEBoolean = new EBooleanElements();
		this.pAudioElement = new AudioElementElements();
		this.pText = new TextElements();
		this.pPicture = new PictureElements();
		this.pVideo = new VideoElements();
		this.pRectangle = new RectangleElements();
		this.pFadeIn = new FadeInElements();
		this.pFadeOut = new FadeOutElements();
		this.pTranslate = new TranslateElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("polytech.spaceteam.cineditor.CinEditor".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Movie:
	//	'Movie' name=EString dimension=Dimension ('fps' fps=EInt)?
	//	layers+=Layer+;
	public MovieElements getMovieAccess() {
		return pMovie;
	}
	
	public ParserRule getMovieRule() {
		return getMovieAccess().getRule();
	}
	
	//Element:
	//	GraphicalElement | FadeIn | FadeOut | Translate | AudioElement;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//Layer:
	//	{Layer}
	//	'Layer'
	//	elements+=Element+;
	public LayerElements getLayerAccess() {
		return pLayer;
	}
	
	public ParserRule getLayerRule() {
		return getLayerAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Position:
	//	'position' ('(' x=ItemPosition ',' y=ItemPosition ')');
	public PositionElements getPositionAccess() {
		return pPosition;
	}
	
	public ParserRule getPositionRule() {
		return getPositionAccess().getRule();
	}
	
	//ItemPosition:
	//	ItemPositionInt | ItemPositionString;
	public ItemPositionElements getItemPositionAccess() {
		return pItemPosition;
	}
	
	public ParserRule getItemPositionRule() {
		return getItemPositionAccess().getRule();
	}
	
	//ItemPositionInt:
	//	position=EInt;
	public ItemPositionIntElements getItemPositionIntAccess() {
		return pItemPositionInt;
	}
	
	public ParserRule getItemPositionIntRule() {
		return getItemPositionIntAccess().getRule();
	}
	
	//ItemPositionString:
	//	position=('center' | 'left' | 'right' | 'bottom' | 'top');
	public ItemPositionStringElements getItemPositionStringAccess() {
		return pItemPositionString;
	}
	
	public ParserRule getItemPositionStringRule() {
		return getItemPositionStringAccess().getRule();
	}
	
	//Dimension:
	//	'dimension' width=EInt 'x' height=EInt;
	public DimensionElements getDimensionAccess() {
		return pDimension;
	}
	
	public ParserRule getDimensionRule() {
		return getDimensionAccess().getRule();
	}
	
	//HexadecimalColor:
	//	'color' hexadecimalValue=EString;
	public HexadecimalColorElements getHexadecimalColorAccess() {
		return pHexadecimalColor;
	}
	
	public ParserRule getHexadecimalColorRule() {
		return getHexadecimalColorAccess().getRule();
	}
	
	//TemporalPosition:
	//	'startAt' beginTime=EInt 'startAfter' elementToStartAfter=[Element] | ('startAt' beginTime=EInt | 'startAfter'
	//	elementToStartAfter=[Element]);
	public TemporalPositionElements getTemporalPositionAccess() {
		return pTemporalPosition;
	}
	
	public ParserRule getTemporalPositionRule() {
		return getTemporalPositionAccess().getRule();
	}
	
	//GraphicalElement:
	//	Text | Video | Picture | Rectangle;
	public GraphicalElementElements getGraphicalElementAccess() {
		return pGraphicalElement;
	}
	
	public ParserRule getGraphicalElementRule() {
		return getGraphicalElementAccess().getRule();
	}
	
	//Margin:
	//	type=MARGIN_NAME '(' size=EInt marginColor=HexadecimalColor? ('opacity' marginColorOpacity=EFloat)? ')';
	public MarginElements getMarginAccess() {
		return pMargin;
	}
	
	public ParserRule getMarginRule() {
		return getMarginAccess().getRule();
	}
	
	//enum MARGIN_NAME:
	//	BOTTOM='bottom' | LEFT='left' | RIGHT='right' | TOP='top';
	public MARGIN_NAMEElements getMARGIN_NAMEAccess() {
		return eMARGIN_NAME;
	}
	
	public EnumRule getMARGIN_NAMERule() {
		return getMARGIN_NAMEAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EFloat ecore::EFloat:
	//	'-'? INT (('.' | ',') INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//AudioElement:
	//	'Audio' name=EString '=' url=EString ('volume' volume=EFloat)? ('fadeIn' fadeIn=EInt)? ('fadeOut' fadeOut=EInt)?
	//	temporalPosition=TemporalPosition? ('cropAt' beginCropTime=EInt)? 'during' duration=EInt;
	public AudioElementElements getAudioElementAccess() {
		return pAudioElement;
	}
	
	public ParserRule getAudioElementRule() {
		return getAudioElementAccess().getRule();
	}
	
	//Text:
	//	'Text' name=EString '=' text=EString ('fontSize' fontSize=EInt)? position=Position? ('margins(' margins+=Margin+
	//	')')? temporalPosition=TemporalPosition? ('during' duration=EInt)? color=HexadecimalColor;
	public TextElements getTextAccess() {
		return pText;
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}
	
	//Picture:
	//	'Picture' name=EString '=' url=EString position=Position? dimension=Dimension? ('margins(' margins+=Margin+ ')')?
	//	temporalPosition=TemporalPosition? ('during' duration=EInt)?;
	public PictureElements getPictureAccess() {
		return pPicture;
	}
	
	public ParserRule getPictureRule() {
		return getPictureAccess().getRule();
	}
	
	//Video:
	//	'Video' name=EString '=' url=EString ('audio' enableAudio=EBoolean)? position=Position? dimension=Dimension?
	//	('margins(' margins+=Margin+ ')')? temporalPosition=TemporalPosition? ('cropAt' beginCropTime=EInt)? 'during'
	//	duration=EInt;
	public VideoElements getVideoAccess() {
		return pVideo;
	}
	
	public ParserRule getVideoRule() {
		return getVideoAccess().getRule();
	}
	
	//Rectangle:
	//	'Rectangle' name=EString '=' color=HexadecimalColor position=Position? dimension=Dimension? ('margins('
	//	margins+=Margin+ ')')? temporalPosition=TemporalPosition? ('during' duration=EInt)?;
	public RectangleElements getRectangleAccess() {
		return pRectangle;
	}
	
	public ParserRule getRectangleRule() {
		return getRectangleAccess().getRule();
	}
	
	//FadeIn:
	//	'Effect' name=EString '=' 'FadeIn' 'during' duration=EInt 'on' '[' elements+=[GraphicalElement] (','
	//	elements+=[GraphicalElement])* ']';
	public FadeInElements getFadeInAccess() {
		return pFadeIn;
	}
	
	public ParserRule getFadeInRule() {
		return getFadeInAccess().getRule();
	}
	
	//FadeOut:
	//	'Effect' name=EString '=' 'FadeOut' 'during' duration=EInt 'on' '[' elements+=[GraphicalElement] (','
	//	elements+=[GraphicalElement])* ']';
	public FadeOutElements getFadeOutAccess() {
		return pFadeOut;
	}
	
	public ParserRule getFadeOutRule() {
		return getFadeOutAccess().getRule();
	}
	
	//Translate:
	//	'Effect' name=EString '=' 'Translate' positionToTranslate=Position temporalPosition=TemporalPosition? ('during'
	//	duration=EInt)? 'on' '[' elements+=[GraphicalElement] (',' elements+=[GraphicalElement])* ']';
	public TranslateElements getTranslateAccess() {
		return pTranslate;
	}
	
	public ParserRule getTranslateRule() {
		return getTranslateAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
