/**
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import polytech.spaceteam.cineditor.ui.AbstractCinEditorUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CinEditorUiModule extends AbstractCinEditorUiModule {
  public CinEditorUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
