/*
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import polytech.spaceteam.cineditor.ui.internal.CineditorActivator;

public class CinEditorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CineditorActivator.getInstance().getInjector("polytech.spaceteam.cineditor.CinEditor");
	}

}
