/*
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CinEditorAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("polytech/spaceteam/cineditor/parser/antlr/internal/InternalCinEditor.tokens");
	}
}
