/**
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.scoping;

import polytech.spaceteam.cineditor.scoping.AbstractCinEditorScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CinEditorScopeProvider extends AbstractCinEditorScopeProvider {
}
