/*
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCinEditorScopeProvider extends DelegatingScopeProvider {
}
