/*
 * generated by Xtext 2.14.0
 */
package polytech.spaceteam.cineditor.serializer;

import CinEditorML.CinEditorMLPackage;
import CinEditorML.FadeIn;
import CinEditorML.FadeOut;
import CinEditorML.Layer;
import CinEditorML.Movie;
import CinEditorML.Picture;
import CinEditorML.Position;
import CinEditorML.Rectangle;
import CinEditorML.Text;
import CinEditorML.Translate;
import CinEditorML.Video;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import polytech.spaceteam.cineditor.services.CinEditorGrammarAccess;

@SuppressWarnings("all")
public class CinEditorSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private CinEditorGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == CinEditorMLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case CinEditorMLPackage.FADE_IN:
				sequence_FadeIn(context, (FadeIn) semanticObject); 
				return; 
			case CinEditorMLPackage.FADE_OUT:
				sequence_FadeOut(context, (FadeOut) semanticObject); 
				return; 
			case CinEditorMLPackage.LAYER:
				sequence_Layer(context, (Layer) semanticObject); 
				return; 
			case CinEditorMLPackage.MOVIE:
				sequence_Movie(context, (Movie) semanticObject); 
				return; 
			case CinEditorMLPackage.PICTURE:
				sequence_Picture(context, (Picture) semanticObject); 
				return; 
			case CinEditorMLPackage.POSITION:
				sequence_Position(context, (Position) semanticObject); 
				return; 
			case CinEditorMLPackage.RECTANGLE:
				sequence_Rectangle(context, (Rectangle) semanticObject); 
				return; 
			case CinEditorMLPackage.TEXT:
				sequence_Text(context, (Text) semanticObject); 
				return; 
			case CinEditorMLPackage.TRANSLATE:
				sequence_Translate(context, (Translate) semanticObject); 
				return; 
			case CinEditorMLPackage.VIDEO:
				sequence_Video(context, (Video) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Element returns FadeIn
	 *     FadeIn returns FadeIn
	 *
	 * Constraint:
	 *     (name=EString beginTime=EInt duration=EInt element=[Element|ID])
	 */
	protected void sequence_FadeIn(ISerializationContext context, FadeIn semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.EFFECT__ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.EFFECT__ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFadeInAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getFadeInAccess().getBeginTimeEIntParserRuleCall_5_0(), semanticObject.getBeginTime());
		feeder.accept(grammarAccess.getFadeInAccess().getDurationEIntParserRuleCall_7_0(), semanticObject.getDuration());
		feeder.accept(grammarAccess.getFadeInAccess().getElementElementIDTerminalRuleCall_9_0_1(), semanticObject.eGet(CinEditorMLPackage.Literals.EFFECT__ELEMENT, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Element returns FadeOut
	 *     FadeOut returns FadeOut
	 *
	 * Constraint:
	 *     (name=EString beginTime=EInt duration=EInt element=[Element|ID])
	 */
	protected void sequence_FadeOut(ISerializationContext context, FadeOut semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.EFFECT__ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.EFFECT__ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFadeOutAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getFadeOutAccess().getBeginTimeEIntParserRuleCall_5_0(), semanticObject.getBeginTime());
		feeder.accept(grammarAccess.getFadeOutAccess().getDurationEIntParserRuleCall_7_0(), semanticObject.getDuration());
		feeder.accept(grammarAccess.getFadeOutAccess().getElementElementIDTerminalRuleCall_9_0_1(), semanticObject.eGet(CinEditorMLPackage.Literals.EFFECT__ELEMENT, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Layer returns Layer
	 *
	 * Constraint:
	 *     elements+=Element+
	 */
	protected void sequence_Layer(ISerializationContext context, Layer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Movie returns Movie
	 *
	 * Constraint:
	 *     (name=EString position=Position layers+=Layer+)
	 */
	protected void sequence_Movie(ISerializationContext context, Movie semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Element returns Picture
	 *     Picture returns Picture
	 *
	 * Constraint:
	 *     (name=EString url=EString position=Position beginTime=EInt duration=EInt)
	 */
	protected void sequence_Picture(ISerializationContext context, Picture semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.PICTURE__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.PICTURE__URL));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__POSITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__POSITION));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPictureAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPictureAccess().getUrlEStringParserRuleCall_4_0(), semanticObject.getUrl());
		feeder.accept(grammarAccess.getPictureAccess().getPositionPositionParserRuleCall_6_0(), semanticObject.getPosition());
		feeder.accept(grammarAccess.getPictureAccess().getBeginTimeEIntParserRuleCall_8_0(), semanticObject.getBeginTime());
		feeder.accept(grammarAccess.getPictureAccess().getDurationEIntParserRuleCall_10_0(), semanticObject.getDuration());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Position returns Position
	 *
	 * Constraint:
	 *     (width=EInt height=EInt (x=EInt y=EInt)?)
	 */
	protected void sequence_Position(ISerializationContext context, Position semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Element returns Rectangle
	 *     Rectangle returns Rectangle
	 *
	 * Constraint:
	 *     (name=EString hexadecimalValue=EString position=Position beginTime=EInt duration=EInt)
	 */
	protected void sequence_Rectangle(ISerializationContext context, Rectangle semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.SHAPE__HEXADECIMAL_VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.SHAPE__HEXADECIMAL_VALUE));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__POSITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__POSITION));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRectangleAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRectangleAccess().getHexadecimalValueEStringParserRuleCall_3_0(), semanticObject.getHexadecimalValue());
		feeder.accept(grammarAccess.getRectangleAccess().getPositionPositionParserRuleCall_4_0(), semanticObject.getPosition());
		feeder.accept(grammarAccess.getRectangleAccess().getBeginTimeEIntParserRuleCall_6_0(), semanticObject.getBeginTime());
		feeder.accept(grammarAccess.getRectangleAccess().getDurationEIntParserRuleCall_8_0(), semanticObject.getDuration());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Element returns Text
	 *     Text returns Text
	 *
	 * Constraint:
	 *     (name=EString text=EString position=Position beginTime=EInt duration=EInt)
	 */
	protected void sequence_Text(ISerializationContext context, Text semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.TEXT__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.TEXT__TEXT));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__POSITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__POSITION));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTextAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTextAccess().getTextEStringParserRuleCall_3_0(), semanticObject.getText());
		feeder.accept(grammarAccess.getTextAccess().getPositionPositionParserRuleCall_4_0(), semanticObject.getPosition());
		feeder.accept(grammarAccess.getTextAccess().getBeginTimeEIntParserRuleCall_6_0(), semanticObject.getBeginTime());
		feeder.accept(grammarAccess.getTextAccess().getDurationEIntParserRuleCall_8_0(), semanticObject.getDuration());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Element returns Translate
	 *     Translate returns Translate
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         pixelsToTranslateHorizontally=EInt 
	 *         pixelsToTranslateVertically=EInt 
	 *         beginTime=EInt 
	 *         duration=EInt 
	 *         element=[Element|ID]
	 *     )
	 */
	protected void sequence_Translate(ISerializationContext context, Translate semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.TRANSLATE__PIXELS_TO_TRANSLATE_HORIZONTALLY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.TRANSLATE__PIXELS_TO_TRANSLATE_HORIZONTALLY));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.TRANSLATE__PIXELS_TO_TRANSLATE_VERTICALLY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.TRANSLATE__PIXELS_TO_TRANSLATE_VERTICALLY));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.EFFECT__ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.EFFECT__ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTranslateAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTranslateAccess().getPixelsToTranslateHorizontallyEIntParserRuleCall_5_0(), semanticObject.getPixelsToTranslateHorizontally());
		feeder.accept(grammarAccess.getTranslateAccess().getPixelsToTranslateVerticallyEIntParserRuleCall_7_0(), semanticObject.getPixelsToTranslateVertically());
		feeder.accept(grammarAccess.getTranslateAccess().getBeginTimeEIntParserRuleCall_10_0(), semanticObject.getBeginTime());
		feeder.accept(grammarAccess.getTranslateAccess().getDurationEIntParserRuleCall_12_0(), semanticObject.getDuration());
		feeder.accept(grammarAccess.getTranslateAccess().getElementElementIDTerminalRuleCall_14_0_1(), semanticObject.eGet(CinEditorMLPackage.Literals.EFFECT__ELEMENT, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Element returns Video
	 *     Video returns Video
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         url=EString 
	 *         beginCropTime=EInt 
	 *         position=Position 
	 *         beginTime=EInt 
	 *         duration=EInt
	 *     )
	 */
	protected void sequence_Video(ISerializationContext context, Video semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.VIDEO__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.VIDEO__URL));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.VIDEO__BEGIN_CROP_TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.VIDEO__BEGIN_CROP_TIME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__POSITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__POSITION));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__BEGIN_TIME));
			if (transientValues.isValueTransient(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CinEditorMLPackage.Literals.ELEMENT__DURATION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVideoAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getVideoAccess().getUrlEStringParserRuleCall_4_0(), semanticObject.getUrl());
		feeder.accept(grammarAccess.getVideoAccess().getBeginCropTimeEIntParserRuleCall_7_0(), semanticObject.getBeginCropTime());
		feeder.accept(grammarAccess.getVideoAccess().getPositionPositionParserRuleCall_8_0(), semanticObject.getPosition());
		feeder.accept(grammarAccess.getVideoAccess().getBeginTimeEIntParserRuleCall_10_0(), semanticObject.getBeginTime());
		feeder.accept(grammarAccess.getVideoAccess().getDurationEIntParserRuleCall_12_0(), semanticObject.getDuration());
		feeder.finish();
	}
	
	
}
